FROM nginx:alpine
COPY ./frontend/pages /usr/share/nginx/html
COPY ./frontend/css /usr/share/nginx/html/css
COPY ./frontend/js /usr/share/nginx/html/js
COPY ./frontend/images /usr/share/nginx/html/images
COPY ./frontend/pdf /usr/share/nginx/html/pdf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80