# Этап сборки
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev

# Финальный образ
FROM node:18-alpine
WORKDIR /app

# Установка Chromium и системных зависимостей для Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    fontconfig

# Отключаем скачивание встроенного Chrome и указываем путь к системному
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Создаём симлинк (на всякий случай)
RUN ln -s /usr/bin/chromium /usr/bin/chromium-browser

COPY --from=builder /app/node_modules ./node_modules
COPY . .

EXPOSE 3001
CMD ["node", "backend/server.js"]